### PR TITLE
Replaces patrun with blommrun

### LINKED ISSUE #6: Add Bloomrun over Patrun
Bloomrun is far faster (3x - 10x) than Patrun, it also supports index & depth first (which are equally valid).

The only concern I have right now is mu uses `*` over `\*\` for regex. This means we either,

- Change mu to do the conversion
- Change bloomrun to do the conversion

@mcollina thoughts on this?

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #6.

Please review @mcdonnelldean @pelger @lucamaraschi

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
LGTM, `'*'` is still something handled by mu directly right?

**Comment by mcollina** [comment]
Passing `'*'` will set a `bloomrun.default()`, see https://github.com/apparatus/mu/pull/20/files#diff-40170a79ab463544c6bab24a821bd6c9R39

**Comment by mcollina** [comment]
Nice that the coverage decreased because it is removing 10 lines of covered code. 😢

**Comment by mcdonnelldean** [comment]
@mcollina Ah yeah, I see it. In that case LGTM. Talk to @pelger about coverage :D

**Comment by lucamaraschi** [comment]
LGTM...we will be missing patrun!

**Comment by davidmarkclements** [comment]
so... Who's going to merge?

@pelger can anyone on the mu team merge?

**Pull request merged**
